### ISSUE TITLE
Edit Models

### ISSUE THREAD

**Issue by dnoneill** [dnoneill/libraryproject#3]
Book model should include following fields:
title
isbn
small_image_url
publisher
num_pages
url
series_works
publication_year
publication_day
publication_month
description

plus whatever we want to add.

Also the ID fields look wrong.  I am not sure what a UUIDField is but I thought it was supposed to be a foreign key field.
Also Loans should include a borrower field

**Comment by albaedesa** [comment]
Got it for book model!
UUID Fields generate random and unique ID strings automatically.
I used it because I thought we wanted each loan object to have its own unique identifier.

Did you want the loanID to be linked to the ID field in the Books model? In that case, I think I would need a type of foreign key field.

**Comment by dnoneill** [comment]
@albaedesa I know what a UUID is, I just am wondering why we would want such a long string, when ForeignKeyField will create a unique identifier for us.  I think that loanid should load the data from books.

**Comment by albaedesa** [comment]
Oh okay, I misunderstood what we needed, sorry!
I'll work on this tonight. :)
